POST http://localhost:3001/api/player/3/quests 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVpcyBBbmRyZWkgT3Vhbm8iLCJpZCI6MywidXNlcm5hbWUiOiJ3aXN3aXNzIiwiaWF0IjoxNzMxMTQ0NTQyfQ.qpUPvVqha_C4aWerFyC-aG-eFUn6KjeTxXBKh-e7jCs

{
  "title": "GRAAAHHHHHHHH",
  "description": "SHAWTY PLEASE DON'T PLAY WITH ME",
  "questType": "DAILY_QUEST",
  "dueDate": "2024-11-20T23:59:59.999Z",
  "difficulty": "MEDIUM",
  "runAt": "2024-11-27T12:34:56.789Z"
}