GET http://localhost:3001/api/player/1/quests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoid2lzd2lzcyIsImlkIjoxLCJpYXQiOjE3MzAwODU2ODV9.cjrfxZFR6g-hEuVeg33-0TVbfdviEBztaJnPCfDoL0Q