export const items = [
  {
    id: 1,
    itemName: 1,
    itemImg: "src/assets/items/a_plus.gif",
    description:
      "The only time I earned this is when I edited it on my professor's pc.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 2,
    itemName: "Adventure Compass",
    itemImg: "src/assets/items/adventure_compass.gif",
    description:
      "Navigate through life's twists and turns with confidence, and you'll never feel lost or un-compass-ionate about your choices.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 3,
    itemName: "Adventure Ticket",
    itemImg: "src/assets/items/adventure_ticket.png",
    description: "Adventure time, grab your ticket!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 4,
    itemName: "Adventure Voucher",
    itemImg: "src/assets/items/adventure_voucher.png",
    description: "Grandma printed me off this voucher for one free box!",
    price: 500,
    rarity: "UNCOMMON",
  },
  {
    id: 5,
    itemName: "Aetheryx's Flower",
    itemImg: "src/assets/items/aetheryxs_flower.png",
    description: "A decomposing red flower, a wisp of its former self.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 6,
    itemName: "Aha's Pitcher Plant",
    itemImg: "src/assets/items/ahas_pitcher_plant.gif",
    description: "I tried pouring lemonade in the pitcher\u2026",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 7,
    itemName: "Aiphey's Gemstone",
    itemImg: "src/assets/items/aipheys_gemstone.png",
    description:
      "Aiphey's gemstone is a precious stone. It vibrates at a high frequency, creating a bubble of spiritual protection against negative energy. It is such a sacred and a rare stone, if you ever manage to get it, you must protect it at all costs.",
    price: 2500,
    rarity: "RARE",
  },
  {
    id: 8,
    itemName: "Alcohol",
    itemImg: "src/assets/items/alcohol.png",
    description: "This is the cheap stuff. Not quite Bud Lite, but similar.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 9,
    itemName: "Alien Sample",
    itemImg: "src/assets/items/alien_sample.gif",
    description: "This is payback for the samples they've taken from us!",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 10,
    itemName: "Ammo",
    itemImg: "src/assets/items/ammo.png",
    description: "Does this ammo even fit the hunting rifle?",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 11,
    itemName: "Ant",
    itemImg: "src/assets/items/ant.png",
    description: 'The movie "Antz" is in fact one of the movies of all time.',
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 12,
    itemName: "Anti-Rob Pack",
    itemImg: "src/assets/items/anti-rob_pack.png",
    description:
      "Try not to get robbed. Unless you're into that, then do what you want.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 13,
    itemName: "Apple",
    itemImg: "src/assets/items/apple.png",
    description:
      "Sweet apples are better than tart, no one will change my mind.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 14,
    itemName: "Apron",
    itemImg: "src/assets/items/apron.png",
    description:
      "A handmade pink apron, finely crafted for Michelin Star chefs, is mainly found in the kitchen.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 15,
    itemName: "Armpit Hair",
    itemImg: "src/assets/items/armpit_hair.png",
    description: "It tastes funny!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 16,
    itemName: "Baby",
    itemImg: "src/assets/items/baby.png",
    description:
      "This is a virtual baby. Not a real baby. Needed to clear that up for some people.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 17,
    itemName: "Badosz's Card",
    itemImg: "src/assets/items/badoszs_card.gif",
    description: "A real king in the sleeve.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 18,
    itemName: "Bait Box",
    itemImg: "src/assets/items/bait_box.gif",
    description:
      "This box contains baits, similar to how I was baited into giving a scammer my credit card info.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 19,
    itemName: "Ban Hammer",
    itemImg: "src/assets/items/ban_hammer.png",
    description:
      "Mods swing this hard and fast, which also happens to be the title of my next se-",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 20,
    itemName: "Bank Note",
    itemImg: "src/assets/items/bank_note.png",
    description:
      "Imagine if banks actually had a max amount. Wait, some do? Thanks Obama.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 21,
    itemName: "Barrel Sludge",
    itemImg: "src/assets/items/barrel_sludge.gif",
    description: "Toxic and stinky, but with something good inside.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 22,
    itemName: "Bean Mp3 Player",
    itemImg: "src/assets/items/bean_Mp3_player.png",
    description:
      "Beans beans, the magical fruit. The more you eat, the more your voice turns into an mp3 file.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 23,
    itemName: "Bean Seeds",
    itemImg: "src/assets/items/bean_seeds.png",
    description:
      "If beans make you fart, does the thing that makes beans make you fart too? Someone test this!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 24,
    itemName: "Bean",
    itemImg: "src/assets/items/bean.png",
    description: "A bean that isn't green.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 25,
    itemName: "Beggars Bowl",
    itemImg: "src/assets/items/beggars_bowl.gif",
    description:
      "Despite being used to beg, I'd put my keys here after a long day at work. The bowl looks cozy.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 26,
    itemName: "Berries and Cream",
    itemImg: "src/assets/items/berries_Cream.png",
    description:
      "Use this item to send it to someone who loves berries and cream!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 27,
    itemName: "Big Brain",
    itemImg: "src/assets/items/big_brain.gif",
    description:
      "A brain so massive that it simply CANNOT be a discord user. Therefore, we sellin this shit for profit.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 28,
    itemName: "Binary",
    itemImg: "src/assets/items/binary.gif",
    description: "I dare you to translate this binary into text.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 29,
    itemName: "Birthday Cake",
    itemImg: "src/assets/items/birthday_cake.png",
    description: 'Anything but ice-cream "cake", unless that\'s the lie.',
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 30,
    itemName: "Black Hole",
    itemImg: "src/assets/items/black_hole.png",
    description: "I don't think this is safe to keep around?",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 31,
    itemName: "Blob",
    itemImg: "src/assets/items/blob.gif",
    description:
      "The blob will rise again, look to the sky and ask for forgiveness.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 32,
    itemName: "Blue Plastic Bits",
    itemImg: "src/assets/items/blue_plastic_bits.png",
    description: "Blue is a fan favorite, I especially like Bluey.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 33,
    itemName: "Blue's Plane",
    itemImg: "src/assets/items/blues_plane.gif",
    description:
      "This top-of-the-line aircraft carries only the most prestigious of passengers.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 34,
    itemName: "Boar",
    itemImg: "src/assets/items/boar.png",
    description: "Some people think this item can be a bit boaring.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 35,
    itemName: "Bolt Cutters",
    itemImg: "src/assets/items/bolt_cutters.png",
    description:
      "I made this item to rob from normies without ever failing, now lots of people have it so I had to nerf it to just break a padlock. Lame devs, L.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 36,
    itemName: "Bottle Whiskey",
    itemImg: "src/assets/items/bottle_whiskey.png",
    description: "Whiskey and a little coke, daddy likey",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 37,
    itemName: "Box Box",
    itemImg: "src/assets/items/box_box.gif",
    description: "Box in a box in a box in a box in a box in a box in a box.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 38,
    itemName: "Box Sand",
    itemImg: "src/assets/items/box_sand.png",
    description:
      "How many of you pee'd in the sandbox as children? Well this item takes from that exact sandbox.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 39,
    itemName: "Boxed Chocolates",
    itemImg: "src/assets/items/boxed_chocolates.png",
    description: "Life is like a chocolate of boxes. Wait, that's not right.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 40,
    itemName: "Broccoli Seeds",
    itemImg: "src/assets/items/broccoli_seeds.png",
    description:
      "Place them somewhere dark and damp and watch them grow to be edible. You just ate damp and old seeds.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 41,
    itemName: "Broccoli",
    itemImg: "src/assets/items/broccoli.png",
    description:
      "Place them somewhere dark and damp and watch them grow to be edible. You just ate damp and old seeds.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 42,
    itemName: "Bundle Box",
    itemImg: "src/assets/items/bundle_box.gif",
    description: "Some evil developer came up with this idea.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 43,
    itemName: "Cactus",
    itemImg: "src/assets/items/cactus.png",
    description:
      "Everyone knows someone who reminds them of what this cactus does, a bit of a prick.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 44,
    itemName: "Cairpirnha",
    itemImg: "src/assets/items/cairpirnha.png",
    description:
      "Don\u2019t worry about what this drink is made of. Worry about proving what you\u2019re made of by drinking it.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 45,
    itemName: "Camera",
    itemImg: "src/assets/items/camera.png",
    description: "Can be used to stream both on Twitch AND onlyfans!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 46,
    itemName: "Candy Cane",
    itemImg: "src/assets/items/candy_cane.png",
    description:
      "I get that it is candy, but how is it a cane? It is way too small to use to walk.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 47,
    itemName: "Candy Corn",
    itemImg: "src/assets/items/candy_corn.png",
    description:
      "I'm starting to think whoever developed this bot just really likes corn.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 48,
    itemName: "Candy",
    itemImg: "src/assets/items/candy.png",
    description: "It is not saltwater taffy. Unless\u2026",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 49,
    itemName: "Carrot Seeds",
    itemImg: "src/assets/items/carrot_seeds.png",
    description:
      "Plant these to grow cucumbers that are orange and help you see in the dark.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 50,
    itemName: "Carrot",
    itemImg: "src/assets/items/carrot.png",
    description: "Bottom. Top was taken by the comedian.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 51,
    itemName: "Cell Phone",
    itemImg: "src/assets/items/cell_phone.png",
    description:
      "Back in my day these flipped open and shut. Wait they brought that back?",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 52,
    itemName: "Chads Weights",
    itemImg: "src/assets/items/chads_weights.png",
    description:
      "He doesn't need these anymore, he's got a permanant gains buff.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 53,
    itemName: "Chets Usb",
    itemImg: "src/assets/items/chets_usb.gif",
    description:
      "Some say the secret to Chet's success is in this USB. Others say it's just a bunch of cat videos because he's secretly broke.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 54,
    itemName: "Chill Pill",
    itemImg: "src/assets/items/chill_pill.png",
    description: "Chill Phil, take a big ol chill pill.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 55,
    itemName: "Chocolate Cake",
    itemImg: "src/assets/items/chocolate_cake.png",
    description:
      "Everyone loves chocolate cake. EVERYONE. No exceptions. Don't argue with me.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 56,
    itemName: "Christmas Gift",
    itemImg: "src/assets/items/christmas_gift.png",
    description: "Merry Christmas from the Dank Memer team!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 57,
    itemName: "Christmas Tree",
    itemImg: "src/assets/items/christmas_tree.png",
    description:
      "This tree is missing an ornament. Must have fallen and broke back in 2005.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 58,
    itemName: "Coin Bomb",
    itemImg: "src/assets/items/coin_bomb.gif",
    description:
      "This is not safe to take on planes. Not because it's a weapon, but because the pilots would leave the cockpit to partake.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 59,
    itemName: "Coin Nuke",
    itemImg: "src/assets/items/coin_nuke.gif",
    description: "Sometimes a coin BOMB isn't enough. Duke would be proud.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 60,
    itemName: "Coin Voucher",
    itemImg: "src/assets/items/coin_voucher.png",
    description:
      "Sometimes you need an item to turn into coins. This is that item, duh.",
    price: 500,
    rarity: "UNCOMMON",
  },
  {
    id: 61,
    itemName: "Cooked Eggs",
    itemImg: "src/assets/items/cooked_eggs.gif",
    description:
      "Did you know pepe lays eggs? Us neither, it freaked us out and I'm not sure where to go from here.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 62,
    itemName: "Cookie",
    itemImg: "src/assets/items/cookie.png",
    description:
      "They said don't eat the dough raw, but that will NOT stop me.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 63,
    itemName: "Corn Seeds",
    itemImg: "src/assets/items/corn_seeds.png",
    description:
      "Corn cobs? Rare? Let's make an entire feature around growing more.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 64,
    itemName: "Corncob",
    itemImg: "src/assets/items/corncob.png",
    description: "Corny jokes are the life blood of this bot.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 65,
    itemName: "Corndog",
    itemImg: "src/assets/items/corndog.png",
    description:
      "Ok so hear me out man, it's pork or beef wrapped in a cornbread breading. I call it... the CORN DOG! Wait why are dogs involved?",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 66,
    itemName: "Cowboy Boots",
    itemImg: "src/assets/items/cowboy_boots.png",
    description:
      "Wear these as a SPUR of the moment fashion choice you coward!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 67,
    itemName: "Cowboy Hat",
    itemImg: "src/assets/items/cowboy_hat.png",
    description: "Doug Dimmadome would be proud of this.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 68,
    itemName: "Credit Card",
    itemImg: "src/assets/items/credit_card.png",
    description: "My mom will never know this is missing.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 69,
    itemName: "Crunchy Taco",
    itemImg: "src/assets/items/crunchy_taco.png",
    description: "This is a beef taco, but we all know fish tacos are better.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 70,
    itemName: "Crypto Scam Coin",
    itemImg: "src/assets/items/crypto_scam_coin.gif",
    description:
      "I will not comment on the state of crypto. I will not comment on the state of crypto. I will not comment on the state of crypto.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 71,
    itemName: "Cupid's Bigtoe",
    itemImg: "src/assets/items/cupids_bigtoe.png",
    description:
      "Cupid lost this in a bet. I took it fair and square, legally of course.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 72,
    itemName: "Cursed Pepe",
    itemImg: "src/assets/items/cursed_pepe.png",
    description: "A pepe that not even a mother could love... But I sure do.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 73,
    itemName: "D100",
    itemImg: "src/assets/items/d100.gif",
    description:
      "This d100 is for display only. Trying to roll it would certainly break it every time. You can obtain this from winning a d100 random event!",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 74,
    itemName: "Daily Box",
    itemImg: "src/assets/items/daily_box.gif",
    description: "A box FROM daily commands, not DAILY gained. Smh users.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 75,
    itemName: "Dank Box",
    itemImg: "src/assets/items/dank_box.gif",
    description:
      "Every time I open these the contents are wet. I hate Dank rewards.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 76,
    itemName: "Dank Memers Hard drive",
    itemImg: "src/assets/items/dank_memers_hardDrive.gif",
    description:
      "The developers dropped this in the water. Who wants free currency?",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 77,
    itemName: "Deer",
    itemImg: "src/assets/items/deer.png",
    description:
      "Bambi deserved better than this, but man oh man is the jerky gonna be good.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 78,
    itemName: "Delta 9 Seeds",
    itemImg: "src/assets/items/delta9_seeds.png",
    description: "Don't STRAIN too hard to farm this.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 79,
    itemName: "Delta 9",
    itemImg: "src/assets/items/delta9.png",
    description:
      "Not as fruitful as blue meth, but way less illegal (in some places). How does this yield so few usable bits? Weird game design.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 80,
    itemName: "Delta 9 Roll",
    itemImg: "src/assets/items/delta9_roll.gif",
    description: "Light a roll and chill until the buzz wears off.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 81,
    itemName: "Designer Hoodie",
    itemImg: "src/assets/items/designer_hoodie.png",
    description: "Using this item gives you black embed colors.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 82,
    itemName: "Developer Box",
    itemImg: "src/assets/items/developer_box.gif",
    description:
      "Each developer item earned gives a little more of their soul away. Like in Harry Potter!",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 83,
    itemName: "Devils Horn",
    itemImg: "src/assets/items/devils_horn.gif",
    description:
      "If there's one thing we know for sure, it's that some portion of the population will find the devil sexy.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 84,
    itemName: "Diamond",
    itemImg: "src/assets/items/diamond.png",
    description:
      "Would you rather shine bright like a diamond, or spend 3 of them on a pickaxe. The choice is simple to me.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 85,
    itemName: "Digging Trophy",
    itemImg: "src/assets/items/digging_trophy.png",
    description: "Me? Personally? I'm digging it.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 86,
    itemName: "Dragon",
    itemImg: "src/assets/items/dragon.gif",
    description:
      "In DnD 5e, an adult red dragon is chaotic evil and has a challenge rating of 17. You're telling me someone shot this one with a rifle?",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 87,
    itemName: "Duck",
    itemImg: "src/assets/items/duck.png",
    description:
      "Ducks lay eggs very similarly edible to chicken eggs. One of my favorite differences are that they can be blue depending on the breed of duck.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 88,
    itemName: "Duct Tape",
    itemImg: "src/assets/items/duct_tape.png",
    description:
      "This item can be used to craft things with the craft command.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 89,
    itemName: "Ectoplasm",
    itemImg: "src/assets/items/ectoplasm.gif",
    description: "Ew, ghost gunk. Disgusting. Funky wunky ghosty gunky.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 90,
    itemName: "Electrifying Zing",
    itemImg: "src/assets/items/electrifying_zing.gif",
    description:
      'Ignite your taste buds with the "Electrifying Zing" \u2014 a culinary sensation that harnesses the electrifying essence of the electric eel, delivering a harmonious fusion of flavors that will leave you buzzing with culinary delight.',
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 91,
    itemName: "Elf On the shelf",
    itemImg: "src/assets/items/elf_ontheshelf.png",
    description:
      "Chippy is angry and chippy is going to make that YOUR problem.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 92,
    itemName: "Embalming Fluid",
    itemImg: "src/assets/items/embalming_fluid.gif",
    description: "The dead drink it, but drinking it also results in death.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 93,
    itemName: "Empowered Fart Bottle",
    itemImg: "src/assets/items/empowered_fart_bottle.gif",
    description:
      "This is like a fart bottle but like, without the downsides. Crazy item design right?",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 94,
    itemName: "Enchanted Badosz Card",
    itemImg: "src/assets/items/enchanted_badosz_card.gif",
    description:
      "It's a Badosz card, but enchanted. If only the enchantment DID something!",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 95,
    itemName: "Energy Drink",
    itemImg: "src/assets/items/energy_drink.png",
    description:
      "Guess the brand that inspired this art. Nope, wrong. It was bud lite.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 96,
    itemName: "Engagement Ring",
    itemImg: "src/assets/items/engagement_ring.png",
    description: "Marriage in a MEME game? Disgusting.",
    price: 2500,
    rarity: "RARE",
  },
  {
    id: 97,
    itemName: "Exclusive Gem Box",
    itemImg: "src/assets/items/exclusive_gem_box.gif",
    description: "Gold Gold Gold Gold Gold Titan Holo Titan Holo",
    price: 50000,
    rarity: "LEGENDARY",
  },
  {
    id: 98,
    itemName: "Fake Id",
    itemImg: "src/assets/items/fake_id.png",
    description:
      "McLovin would be proud of the quality of this expensive and very real ID.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 99,
    itemName: "Fart In A bottle",
    itemImg: "src/assets/items/fart_in_abottle.png",
    description:
      "You're either a smart fella or a fart smella.\" -TheLazyTownie",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 100,
    itemName: "Fertilizer Bag",
    itemImg: "src/assets/items/fertilizer_bag.png",
    description:
      "Fertilize me\", now without Ammonium nitrate because that's not good",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 101,
    itemName: "Fidget Spinner",
    itemImg: "src/assets/items/fidget_spinner.gif",
    description: "Once a stimulation tool, now a bad meme.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 102,
    itemName: "Fierce Fang Fare",
    itemImg: "src/assets/items/fierce_fang_fare.gif",
    description:
      'Embrace the wild side of your palate with "Fierce Fang Fare" \u2014 a tantalizing culinary creation that unleashes the bold flavors of the ferocious piranha, leaving you craving for more.',
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 103,
    itemName: "Figures Watch",
    itemImg: "src/assets/items/figures_watch.gif",
    description:
      "The time on this watch seems all out of whack. What's up with this guy?",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 104,
    itemName: "Fishing Trophy",
    itemImg: "src/assets/items/fishing_trophy.png",
    description:
      "Once upon a time, to get this trophy you had to shove hundreds of fish into a crafting bench.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 105,
    itemName: "Fools Notif",
    itemImg: "src/assets/items/fools_notif.gif",
    description: "An item for fools. NO I meant April fools\u2026",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 106,
    itemName: "Fossil",
    itemImg: "src/assets/items/fossil.png",
    description: "How did my grandmother get into this bot as an item?",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 107,
    itemName: "Freemium Ad",
    itemImg: "src/assets/items/freemium_ad.gif",
    description:
      "You saw some ads, so you get an ad. Collect these to flex on how much you support the devs via seeing ads.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 108,
    itemName: "Fresh Bread",
    itemImg: "src/assets/items/fresh_bread.png",
    description:
      "Idk how fresh this bread can be when it sits in sweaty Dank Memer player inventories all day.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 109,
    itemName: "Friends Gift",
    itemImg: "src/assets/items/friends_gift.png",
    description:
      "Why do you have your friend's gift still, give it to them already.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 110,
    itemName: "Garbage",
    itemImg: "src/assets/items/garbage.png",
    description: "What has 6 wheels and flies? A garbage truck!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 111,
    itemName: "Gift Box",
    itemImg: "src/assets/items/gift_box.png",
    description:
      "The lootbox that cannot be opened. The cursed lootbox if you will.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 112,
    itemName: "God Box",
    itemImg: "src/assets/items/god_box.gif",
    description: "This box is the lifeblood of my wallet.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 113,
    itemName: "Golden Coins",
    itemImg: "src/assets/items/golden_coins.png",
    description:
      "The golden coins of Melmsie's appreciation, not worth much but at least normies don't get them.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 114,
    itemName: "Golden Corndog",
    itemImg: "src/assets/items/golden_corndog.png",
    description: "Why is this golden. It does not look edible at all.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 115,
    itemName: "Golden Nugget",
    itemImg: "src/assets/items/golden_nugget.png",
    description: "It looks like a golden doo doo, it must be worth a lot!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 116,
    itemName: "Golden Plastic Bits",
    itemImg: "src/assets/items/golden_plastic_bits.png",
    description:
      "The icon, the legend, the... oh the market price is dropping again",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 117,
    itemName: "Grass",
    itemImg: "src/assets/items/grass.png",
    description:
      "This item is a paradox. If someone owns it they probably do not touch grass, yet they are currently touching grass.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 118,
    itemName: "Gravestone",
    itemImg: "src/assets/items/gravestone.png",
    description:
      "Having this means you died. Unless you bought it from someone else on the market. Imagine buying someone else's gravestone. New black market listing unlocked!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 119,
    itemName: "Green Screen",
    itemImg: "src/assets/items/green_screen.png",
    description:
      "Hide the mess behind you so people don't know you're in shambles.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 120,
    itemName: "Grind Pack",
    itemImg: "src/assets/items/grind_pack.png",
    description: "Grinding can be unhealthy, take breaks and touch grass.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 121,
    itemName: "Grub Pall",
    itemImg: "src/assets/items/grub_pall.gif",
    description: "A pail of grubs that will make you pale and flub.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 122,
    itemName: "Hardhat",
    itemImg: "src/assets/items/hardhat.png",
    description:
      "Worn by the hard working gremlins behind the scenes at Dank Memer HQ while running in circles putting out fires.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 123,
    itemName: "Haunted Box",
    itemImg: "src/assets/items/haunted_box.gif",
    description:
      "This box is packed with 1000 souls of previous dank players. Once they quit, they died and we shoved them in this box. I think that's the right order of events?",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 124,
    itemName: "Headphones",
    itemImg: "src/assets/items/headphones.png",
    description: "Open back is the best quality you'll find in headphones.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 125,
    itemName: "Hoe",
    itemImg: "src/assets/items/hoe.png",
    description:
      "Ain't nobody getting between me and my bros, bros before uh... nevermind.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 126,
    itemName: "Holiday Stocking",
    itemImg: "src/assets/items/holiday_stocking.png",
    description: "Some people call this a sock, I call it a HOLIDAY sock!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 127,
    itemName: "Holy Badosz's Bread",
    itemImg: "src/assets/items/holy_badoszs_bread.gif",
    description:
      "This bread might be holy, but it smells TERRIBLE and probably should not be touched with a ten foot pole. This must be 10,000 years old.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 128,
    itemName: "Holy Water",
    itemImg: "src/assets/items/holy_water.png",
    description:
      "This water is (metaphorically) used to cleanse the eyes of anyone who looked at Badosz.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 129,
    itemName: "Hunting Rifle",
    itemImg: "src/assets/items/hunting_rifle.png",
    description: "Bambi is VERY upset with you. Put it down!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 130,
    itemName: "Hunting Trophy",
    itemImg: "src/assets/items/hunting_trophy.png",
    description:
      "It's a 27 point buck, just believe me and do NOT try and count it.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 131,
    itemName: "Inflated Delicacy",
    itemImg: "src/assets/items/inflated_delicacy.gif",
    description:
      'Indulge in the exquisite "Inflated Delicacy" \u2014 a culinary masterpiece that artfully combines the unique textures and flavors of the pufferfish, creating a truly unforgettable dining experience.',
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 132,
    itemName: "Jack O Lantern",
    itemImg: "src/assets/items/jack_o_lantern.gif",
    description:
      "The name is how it is because I did not want people calling it jack. People did it anyway.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 133,
    itemName: "Jar Of Singularity",
    itemImg: "src/assets/items/jar_of_singularity.png",
    description: "Wait, HOW did they get this in a jar?",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 134,
    itemName: "Joke Book",
    itemImg: "src/assets/items/joke_book.png",
    description:
      "Imagine needing to read a book to be funny. Nice job, unfunny nerd.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 135,
    itemName: "Junk",
    itemImg: "src/assets/items/junk.png",
    description: "What do raccoons eat? Junk food!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 136,
    itemName: "Kables Sunglasses",
    itemImg: "src/assets/items/kables_sunglasses.gif",
    description: "A chad item for virgin staff member.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 137,
    itemName: "Keyboard",
    itemImg: "src/assets/items/keyboard.png",
    description:
      "Why are they called keys? Do they unlock the ability to type?",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 138,
    itemName: "Ladybug",
    itemImg: "src/assets/items/ladybug.png",
    description:
      "Fun fact, not all Lady Bugs are lady bugs. Another fun fact is that these bugs smell like shit.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 139,
    itemName: "Landmine",
    itemImg: "src/assets/items/landmine.png",
    description:
      "Who would have thought a game with pets would also involve landmines.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 140,
    itemName: "Laptop",
    itemImg: "src/assets/items/laptop.png",
    description:
      "Imagine using a laptop instead of a cellphone in 2025, wait it's not 2025 yet carry on.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 141,
    itemName: "Lasso",
    itemImg: "src/assets/items/lasso.png",
    description: "Yeeeeeehaw, I done wrangled me a critter with this!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 142,
    itemName: "Law Degree",
    itemImg: "src/assets/items/law_degree.png",
    description:
      "I got my law degree the same way Mike Ross got his. Walking into the wrong office. Now I want to sell it.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 143,
    itemName: "Legacy Common Fish",
    itemImg: "src/assets/items/legacy_common_fish.png",
    description:
      "This fish is pretty common, unlike my ability to come up with good flavor text.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 144,
    itemName: "Legacy Exotic Fish",
    itemImg: "src/assets/items/legacy_exotic_fish.png",
    description:
      "If this was Minecraft, this fish would be used to feed a pet axolotl",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 145,
    itemName: "Legacy Felly Fish",
    itemImg: "src/assets/items/legacy_felly_fish.png",
    description: "Lucky for you this was not a Box jellyfish, look it up.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 146,
    itemName: "Legacy Fishing Bait",
    itemImg: "src/assets/items/legacy_fishing_bait.png",
    description: "All my homies (fish) love biting this (fake) food.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 147,
    itemName: "Legacy Fishing Pole",
    itemImg: "src/assets/items/legacy_fishing_pole.png",
    description: "It's no Bassmaster 2000 but it should do the job.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 148,
    itemName: "Legacy Kraken",
    itemImg: "src/assets/items/legacy_kraken.png",
    description:
      "This thing is a pain to have around, it's always kraken jokes.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 149,
    itemName: "Legacy Legendary Fish",
    itemImg: "src/assets/items/legacy_legendary_fish.gif",
    description:
      "This fish is only half as legendary as the sailors it has brought to the bottom of the sea.",
    price: 50000,
    rarity: "LEGENDARY",
  },
  {
    id: 150,
    itemName: "Life Saver",
    itemImg: "src/assets/items/life_saver.gif",
    description:
      "When you die with one of these in your inventory, you are saved from death. Found from the professional fisherman job.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 151,
    itemName: "Literally Karen",
    itemImg: "src/assets/items/literally_karen.png",
    description: "She wants to speak to your manager.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 152,
    itemName: "Membership Box",
    itemImg: "src/assets/items/membership_box.gif",
    description: "Pay to win? No way baby this is pay to ENJOY (by winning).",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 153,
    itemName: "Meme Box",
    itemImg: "src/assets/items/meme_box.gif",
    description:
      "You're telling me there is NO memes in this box? Only items and coins? False advertisement???",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 154,
    itemName: "Meteorite",
    itemImg: "src/assets/items/meteorite.gif",
    description: "Thank god this didn't hit the Earth!",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 155,
    itemName: "Microphone",
    itemImg: "src/assets/items/microphone.png",
    description: "Honestly the most important aspect of a streamer's toolkit.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 156,
    itemName: "Mole Man",
    itemImg: "src/assets/items/mole_man.gif",
    description:
      "I suggest seeing your dermatologist about this mole as I'm not sure liquid nitrogen works on things with claws.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 157,
    itemName: "Mouse",
    itemImg: "src/assets/items/mouse.png",
    description: "Why is it called a mouse?",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 158,
    itemName: "Musical Note",
    itemImg: "src/assets/items/musical_note.gif",
    description:
      'A single note is enough to change the world. Of course, only if that note is a written note to a world power telling them "I bet you can\'t nuke that other world power". Has nothing to do with music.',
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 159,
    itemName: "Normie Box",
    itemImg: "src/assets/items/normis_box.gif",
    description:
      "Little box packs a little punch. Not a big punch, it's a normie boxbox.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 160,
    itemName: "Odd Eye",
    itemImg: "src/assets/items/odd_eye.gif",
    description:
      "The only one who could see the dark globule in the distance, and now watches over the rest.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 161,
    itemName: "Old Box",
    itemImg: "src/assets/items/old_box.gif",
    description:
      "Is the box old or the items inside? Ok well that is a bit misleading isn't it.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 162,
    itemName: "Out West Adventure Box",
    itemImg: "src/assets/items/out_west_adventure_box.gif",
    description: "I bet the cactus is thriving in there.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 163,
    itemName: "Pepe Bathwater",
    itemImg: "src/assets/items/pepe_bathwater.gif",
    description:
      "The flavor of pepe's bathwater will remain a mystery to everyone except DMC moderators.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 164,
    itemName: "Pepe Box",
    itemImg: "src/assets/items/pepe_box.gif",
    description:
      "Pepe certainly did NOT hold me at gunpoint to make a pepe themed box. Who got that idea?",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 165,
    itemName: "Pepe Coin",
    itemImg: "src/assets/items/pepe_coin.gif",
    description:
      "Can you even believe that this used to be the most expensive item? Now it's a gift you'd give your cousin as a hand me down.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 166,
    itemName: "Pepe Crown",
    itemImg: "src/assets/items/pepe_crown.png",
    description:
      "Some say pepe personally gifted this crown to those who own it. That would be absurd though.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 167,
    itemName: "Pepe Medal",
    itemImg: "src/assets/items/pepe_medal.gif",
    description:
      "This medal used to be rare, now it's just a secondhand bargain bin item for the rich players.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 168,
    itemName: "Pepe Ribbon",
    itemImg: "src/assets/items/pepe_ribbon.png",
    description:
      "A ribbon? You think I want a RIBBON? Oh it's pepe themed? Count me in.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 169,
    itemName: "Pepe Ring",
    itemImg: "src/assets/items/pepe_ring.png",
    description: "Go go gadget deploy pepe ring! Oh it's just a Collectible.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 170,
    itemName: "Pepe Statue",
    itemImg: "src/assets/items/pepe_statue.png",
    description: "A statue immortalizing pepe, as all statues should.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 171,
    itemName: "Pepe Sus",
    itemImg: "src/assets/items/pepe_sus.gif",
    description: "Pepe... why are you looking so SUS step bro",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 172,
    itemName: "Pepe Trophy",
    itemImg: "src/assets/items/pepe_trophy.gif",
    description:
      "A trophy that is worth its weight in coins. Sadly the weight is much lower than the purchase price.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 173,
    itemName: "Plastic Box",
    itemImg: "src/assets/items/plastic_box.gif",
    description: "Imagine if this box existed when plastics were still\u2026",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 174,
    itemName: "Prestige Coin",
    itemImg: "src/assets/items/prestige_coin.png",
    description:
      "A coin you get in exchange for losing most of your stuff. Seems fair.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 175,
    itemName: "Prestige Pack",
    itemImg: "src/assets/items/prestige_pack.png",
    description:
      "Congrats on prestiging, here is the most basic list of items that will not matter because you stored all your stuff on an alt first.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 176,
    itemName: "Rare Butterfly",
    itemImg: "src/assets/items/rare_butterfly.gif",
    description:
      "A beautiful butterfly in the sky, but I think I can fly twice as high. This item was made for a previous team member, Amathine",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 177,
    itemName: "Reversal Card",
    itemImg: "src/assets/items/reversal_card.gif",
    description:
      "Reversal cards were previously used to reverse a steal someone performed on you. Due to being SUPER buggy and causing multiple exploits, they are no longer functional, and never will be.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 178,
    itemName: "Space Adventure Box",
    itemImg: "src/assets/items/space_adventure_box.gif",
    description: "Do not move, I think I hear a black hole in that box.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 179,
    itemName: "Stack Cash",
    itemImg: "src/assets/items/stack_cash.png",
    description:
      "Wait so you gave me a stack of cash and I have to trade it for only 2 things? This sounds more like a coupon.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 180,
    itemName: "Stonk Coin",
    itemImg: "src/assets/items/stonk_coin.gif",
    description:
      "Rotsevni wanted a stonk coin, so Rotsevni got a stonk coin. Winning our competitions pays off!",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 181,
    itemName: "Sugar Skull",
    itemImg: "src/assets/items/sugar_skull.png",
    description: "Celebrate D\u00eda de los Muertos by using this, yum!",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 182,
    itemName: "Sus Fluid",
    itemImg: "src/assets/items/sus_fluid.png",
    description: "Please do not drink this, I think it came from Craig's room.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 183,
    itemName: "Tool Box",
    itemImg: "src/assets/items/tool_box.gif",
    description:
      "This box contains tools, but it's also owned by tools. Do you own one?",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 184,
    itemName: "Universe Box",
    itemImg: "src/assets/items/universe_box.gif",
    description: "The universe is only as big as you let it be.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 185,
    itemName: "Winning Lottery Ticket",
    itemImg: "src/assets/items/winning_lottery_ticket.png",
    description:
      "Is it even that lucky?? You probably paid 5b to win, p2w p2w p2w- oh that's a lottery.",
    price: 100,
    rarity: "COMMON",
  },
  {
    id: 186,
    itemName: "Work Box",
    itemImg: "src/assets/items/work_box.gif",
    description:
      "Wanna stay home from work and open lootboxes? WOAH TWO IN ONE?",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 187,
    itemName: "ZomB's  ZomBee",
    itemImg: "src/assets/items/zombee.gif",
    description:
      "According to all known laws of the universe, there is no way a bee should be able to come back from the dead. The bee, of course, rises from the dead anyway because bees don't care what humans think is impossible.",
    price: 10000,
    rarity: "EPIC",
  },
  {
    id: 188,
    itemName: "Zombie Hand",
    itemImg: "src/assets/items/zombie_hand.gif",
    description:
      "The hand of the undead. Do NOT even think about doing what you're thinking about doing.",
    price: 10000,
    rarity: "EPIC",
  },
];
